// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npuzxxaiwnvdudgkkgek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wdXp4eGFpd252ZHVkZ2trZ2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3Nzc2MDMsImV4cCI6MjA3OTM1MzYwM30.EuRwOfHDiinMGfEipGll8kVZk9YUsoiV7XXBhrFP3r8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});